- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: ntpd started (rhel)
  service:
    name: ntpd
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: ntp started (debian)
  service:
    name: ntp
    state: started
    enabled: yes
  when: ansible_os_family == 'Debian'
